<template>
    <div>
        <!--导航栏-->
        <nav-menu></nav-menu>
        <div class="main">
            <div class="box">
                <!--个人信息菜单-->
                <profile-menu :menu="profileMenu"></profile-menu>
                <!--个人信息数据-->
                <profile-data></profile-data>
            </div>
        </div>
        <!--页脚-->
        <footer-menu :menu="footerMenu" :qrcode="qrcode"></footer-menu>
    </div>
</template>

<script>
    import NavMenu from "../../components/common/navbar/NavMenu";
    import FooterMenu from "../../components/common/footer/FooterMenu";
    import ProfileMenu from "./childComps/ProfileMenu";
    import ProfileData from "./childComps/ProfileData";

    export default {
        name: "Profile",
        components:{
            NavMenu,
            FooterMenu,
            ProfileMenu,
            ProfileData
        },
        data(){
            return {
                footerMenu:[
                    {
                        "title":"预约点餐服务",
                        "icon":"el-icon-phone",
                        "childs":[
                            {
                                "name":"帮助中心"
                            },
                            {
                                "name":"账户管理"
                            },
                            {
                                "name":"购物指南"
                            },
                            {
                                "name":"订单操作"
                            }
                        ]
                    },
                    {
                        "title":"最新食品预览",
                        "icon":"el-icon-picture",
                        "childs":[
                            {
                                "name":"服务支持"
                            },
                            {
                                "name":"售后政策"
                            },
                            {
                                "name":"自助服务"
                            },
                            {
                                "name":"相关下载"
                            }
                        ]
                    },
                    {
                        "title":"关于我们",
                        "icon":"el-icon-user-solid",
                        "childs":[
                            {
                                "name":"加入我们",
                            },
                            {
                                "name":"了解我们"
                            },
                            {
                                "name":"投资者关系"
                            },
                            {
                                "name":"企业社会责任"
                            }
                        ]
                    },
                    {
                        "title":"帮助中心",
                        "icon":"el-icon-s-help",
                        "childs":[
                            {
                                "name":"礼物码"
                            },
                            {
                                "name":"F码通道"
                            },
                            {
                                "name":"防伪查询"
                            },
                            {
                                "name":"人工客服"
                            }
                        ]
                    },
                    {
                        "title":"线下门店",
                        "icon":"el-icon-s-shop",
                        "childs":[
                            {
                                "name":"鱼米之乡"
                            },
                            {
                                "name":"服务网点"
                            },
                            {
                                "name":"授权餐饮店"
                            },
                            {
                                "name":"诚信经营"
                            }
                        ]
                    }

                ],
                qrcode:[
                    {
                        "image":require("assets/qrcodes/qrcode.jpg"),
                        "link":"https://www.mi.com/"
                    },
                    {
                        "image":require("assets/qrcodes/qrcode.jpg"),
                        "link":"https://www.mi.com/"
                    }
                ],
                profileMenu:[
                    {
                        "name":"订单中心",
                        "icon":"el-icon-sell",
                        "childs":[
                            {
                                "name":"我的订单",
                                "link":"#"
                            },
                            {
                                "name":"评价晒单",
                                "link":"#"
                            },
                            {
                                "name":"花费充值订单",
                                "link":"#"
                            },
                            {
                                "name":"以旧换新订单",
                                "link":"#"
                            }
                        ]
                    },
                    {
                        "name":"个人中心",
                        "icon":"el-icon-s-custom",
                        "childs":[
                            {
                                "name":"我的个人中心",
                                "link":"#"
                            },
                            {
                                "name":"消息通知",
                                "link":"#"
                            },
                            {
                                "name":"购买资格",
                                "link":"#"
                            },
                            {
                                "name":"现金账户",
                                "link":"#"
                            },
                            {
                                "name":"XX礼品卡",
                                "link":"#"
                            },
                            {
                                "name":"XX礼品卡",
                                "link":"#"
                            },
                            {
                                "name":"服务记录",
                                "link":"#"
                            },
                            {
                                "name":"服务记录",
                                "link":"#"
                            },
                            {
                                "name":"服务记录",
                                "link":"#"
                            },
                            {
                                "name":"服务记录",
                                "link":"#"
                            },
                        ]
                    },
                    {
                        "name":"售后服务",
                        "icon":"el-icon-s-help",
                        "childs":[
                            {
                                "name":"服务记录",
                                "link":"#"
                            },
                            {
                                "name":"申请服务",
                                "link":"#"
                            },
                            {
                                "name":"领取快递报销",
                                "link":"#"
                            }
                        ]
                    },
                    {
                        "name":"账户管理",
                        "icon":"el-icon-unlock",
                        "childs":[
                            {
                                "name":"个人信息",
                                "link":"#"
                            },
                            {
                                "name":"修改密码",
                                "link":"#"
                            },
                            {
                                "name":"注销服务",
                                "link":"#"
                            },
                            {
                                "name":"注销服务",
                                "link":"#"
                            },
                            {
                                "name":"注销服务",
                                "link":"#"
                            },
                            {
                                "name":"注销服务",
                                "link":"#"
                            }
                        ]
                    }
                ]
            }
        }
    }
</script>

<style scoped>
    .main{background-color: #52faf0;height: 1100px;}
    .main .box{width: 1410px;height: 1000px;margin: auto;}
</style>
